"""Writes the KAIRO adaptive-icon layers as Android vectors, using the geometry of design/kairo-icon.png
(1024 px space, the same measurements make_icon.py uses). Run from the repo root."""
import math

RES = "app/src/main/res/drawable/"
S0 = 568.0 / 684.0                       # original logo px -> 1024 icon px
def T(p): return ((p[0] - 627.5) * S0 + 512, (p[1] - 503.0) * S0 + 512)

RING_C_O = (627.4, 531.9); RING_R_O = 302.0
ring_c = T(RING_C_O); ring_r = RING_R_O * S0
stroke = 21 * 1.28 * S0                   # ≈ 22.3
gap = math.radians(6.3)
orb_c = T((624.0, 547.0)); orb_r = 200 * 1.10 * S0

stem_x_o = 624.0 - 1.10 * (624.0 - 423.5)
half_o = math.sqrt(RING_R_O ** 2 - (stem_x_o - RING_C_O[0]) ** 2)
stem = (T((stem_x_o, RING_C_O[1] - half_o)), T((stem_x_o, RING_C_O[1] + half_o)))

def ring_hit(p, d):
    px, py = p[0] - RING_C_O[0], p[1] - RING_C_O[1]
    b = px * d[0] + py * d[1]; c = px * px + py * py - RING_R_O ** 2
    t = -b + math.sqrt(b * b - c); return (p[0] + t * d[0], p[1] + t * d[1])
arms = []
for p, d in (((825.5, 381.0), (0.692, -0.722)), ((817.1, 684.0), (0.739, 0.673))):
    arms.append((T((p[0] - 260 * d[0], p[1] - 260 * d[1])), T(ring_hit(p, d))))

BARS = [(397, 535, 575), (434.5, 520, 589), (471, 497, 610), (510.5, 466, 640), (549.5, 497, 610), (588, 520, 589), (624, 535, 575)]
BAR_W = 16
spark = (511.0, 266.0)

# Map 1024 space into the 108 dp adaptive canvas: symbol (ring + spark) centred, ring outer radius ≈ 26 dp,
# so everything sits inside the 66 dp safe zone that every launcher mask keeps.
SCALE = 26.0 / (ring_r + stroke / 2)
sym_top = spark[1] - 14; sym_bottom = ring_c[1] + ring_r + stroke / 2
CY = (sym_top + sym_bottom) / 2
def V(p): return ((p[0] - 512) * SCALE + 54, (p[1] - CY) * SCALE + 54)
def f(x): return ("%.2f" % x).rstrip("0").rstrip(".")
def L(x): return x * SCALE

def circle(c, r):
    return "M%s,%sa%s,%s 0,1 1,0 %sa%s,%s 0,1 1,0 -%sz" % (f(c[0]), f(c[1] - r), f(r), f(r), f(2 * r), f(r), f(r), f(2 * r))

def ring_arc():
    c = V(ring_c); r = L(ring_r)
    # Top is -90°; draw clockwise from just right of the gap round to just left of it.
    a0 = -math.pi / 2 + gap; a1 = -math.pi / 2 - gap + 2 * math.pi
    p0 = (c[0] + r * math.cos(a0), c[1] + r * math.sin(a0)); p1 = (c[0] + r * math.cos(a1), c[1] + r * math.sin(a1))
    return "M%s,%sA%s,%s 0,1 1,%s,%s" % (f(p0[0]), f(p0[1]), f(r), f(r), f(p1[0]), f(p1[1]))

def line(a, b):
    a, b = V(a), V(b); return "M%s,%sL%s,%s" % (f(a[0]), f(a[1]), f(b[0]), f(b[1]))

k_path = ring_arc() + line(*stem) + line(*arms[0]) + line(*arms[1])
bars_path = "".join(line((x, y0 + BAR_W / 2), (x, y1 - BAR_W / 2)) for x, y0, y1 in BARS)
oc = V(orb_c); orr = L(orb_r); sc = V(spark)
sw = f(L(stroke)); bw = f(L(BAR_W))

HEAD = '''<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by design/make_icon_vector.py from the geometry of design/kairo-icon.png. Edit the script, not this file. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:aapt="http://schemas.android.com/aapt"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="108"
    android:viewportHeight="108">
'''
def radial(cx, cy, r, stops):
    items = "\n".join('                <item android:offset="%s" android:color="%s" />' % (o, c) for o, c in stops)
    return '''        <aapt:attr name="android:fillColor">
            <gradient android:type="radial" android:centerX="%s" android:centerY="%s" android:gradientRadius="%s">
%s
            </gradient>
        </aapt:attr>''' % (f(cx), f(cy), f(r), items)

def linear(x0, y0, x1, y1, a, b, attr="strokeColor"):
    return '''        <aapt:attr name="android:%s">
            <gradient android:type="linear" android:startX="%s" android:startY="%s" android:endX="%s" android:endY="%s"
                android:startColor="%s" android:endColor="%s" />
        </aapt:attr>''' % (attr, f(x0), f(y0), f(x1), f(y1), a, b)

rc = V(ring_c); rr = L(ring_r)
fg = HEAD + '''    <!-- Soft blue halo behind everything (vectors can't blur, so a radial fade stands in for the glow). -->
    <path android:pathData="%s">
%s
    </path>
    <!-- Ring with the gap at the top, and the K: stem plus two arms that run under the orb. -->
    <path android:pathData="%s" android:strokeWidth="%s" android:strokeLineCap="butt" android:fillColor="#00000000">
%s
    </path>
    <!-- Orb -->
    <path android:pathData="%s">
%s
    </path>
    <path android:pathData="%s" android:strokeWidth="%s" android:strokeColor="#B39CF4FF" android:fillColor="#00000000" />
    <!-- Voice waveform -->
    <path android:pathData="%s" android:strokeWidth="%s" android:strokeColor="#2600E5FF" android:strokeLineCap="round" />
    <path android:pathData="%s" android:strokeWidth="%s" android:strokeColor="#FFF2FBFF" android:strokeLineCap="round" />
    <!-- Amber spark: the "right moment". -->
    <path android:pathData="%s">
%s
    </path>
    <path android:pathData="%s" android:strokeWidth="%s" android:strokeColor="#FFFFB020" android:strokeLineCap="round" />
    <path android:pathData="%s" android:fillColor="#FFFFE7B0" />
</vector>
''' % (
    circle(rc, rr * 1.32), radial(rc[0], rc[1], rr * 1.32, [("0", "#5C0060E6"), ("0.6", "#2E0050D0"), ("1", "#000040C0")]),
    k_path, sw, linear(rc[0] - rr, rc[1] - rr, rc[0] + rr, rc[1] + rr, "#FF5FF8FE", "#FF00D0FE"),
    circle(oc, orr), radial(oc[0] - orr * 0.25, oc[1] - orr * 0.3, orr * 1.3, [("0", "#FF7FE9FF"), ("0.35", "#FF1E9BFF"), ("0.8", "#FF1554E0"), ("1", "#FF0B36B8")]),
    circle(oc, orr - L(2)), f(L(5)),
    bars_path, f(L(BAR_W * 2.2)), bars_path, bw,
    circle(sc, L(46)), radial(sc[0], sc[1], L(46), [("0", "#99FFB020"), ("1", "#00FFB020")]),
    line((spark[0], spark[1] - 46), (spark[0], spark[1] + 36)), f(L(5)),
    circle(sc, L(14)),
)
open(RES + "ic_launcher_foreground.xml", "w").write(fg)

def from_orb_edge(a, b):
    # Moves an arm's start out to the orb's edge, so a see-through orb doesn't show the arm inside it.
    dx, dy = b[0] - a[0], b[1] - a[1]; n = math.hypot(dx, dy); dx, dy = dx / n, dy / n
    px, py = a[0] - orb_c[0], a[1] - orb_c[1]
    bb = px * dx + py * dy; cc = px * px + py * py - orb_r ** 2
    t = -bb + math.sqrt(bb * bb - cc); return ((a[0] + t * dx, a[1] + t * dy), b)
mono_k = ring_arc() + line(*stem) + "".join(line(*from_orb_edge(*arm)) for arm in arms)

# Monochrome (themed icons, Android 13+): one colour, the launcher tints it. Orb becomes an outline so the
# waveform still reads, and the halo and spark glow are left out.
mono = HEAD + '''    <path android:pathData="%s" android:strokeWidth="%s" android:strokeColor="#FF000000" android:fillColor="#00000000" />
    <path android:pathData="%s" android:fillColor="#FF000000" android:fillAlpha="0.35" />
    <path android:pathData="%s" android:strokeWidth="%s" android:strokeColor="#FF000000" android:fillColor="#00000000" />
    <path android:pathData="%s" android:strokeWidth="%s" android:strokeColor="#FF000000" android:strokeLineCap="round" />
    <path android:pathData="%s" android:fillColor="#FF000000" />
</vector>
''' % (mono_k, sw, circle(oc, orr), circle(oc, orr - L(4)), f(L(8)), bars_path, bw, circle(sc, L(14)))
open(RES + "ic_launcher_monochrome.xml", "w").write(mono)
print("scale", SCALE, "orb r dp", orr, "ring r dp", rr)
